armor = {
    "Vault Suit": 0,
    "Robe": 5,
    "Robes": 5,
    "Police Uniform": 15,
    "Pants": 15,
    "Leather Jacket": 10,
    "Combat Leather Jacket": 10,
    "Leather Armor": 10,
    "Leather Armor Mark II": 10,
    "Thermal Leather Armor": 10,
    "Metal Jacket": 15,
    "Metal Armor": 15,
    "Metal Armor Mark II": 15,
    "Tesla Armor": 15,
    "Bridgekeeper's Robes": 15,
    "Combat Armor": 20,
    "NCR Ranger Armor": 25,
    "Desert Combat Armor": 25,
    "Combat Armor Mark II": 25,
    "Brotherhood Armor": 25,
    "Enclave Armor": 25,
    "Power Armor": 30,
    "Hardened Power Armor": 30,
    "Advanced Power Armor": 30,
    "Adv. Power Armor MKII": 30
}
