big_guns = {
    "Minigun": {
        "perks": ["Accurate"],
        "damage": "12-15",
        "range": 30,
        "ammo": ["5mm JHP", "5mm AP"],
        "ammo_capacity": 120,
        "type": "Gatling Gun",
        "ap": 7,
        "st": 7,
        "hands": 2,
        "attack_types": ["Burst"]
    },
    "Avenger Minigun": {
        "perks": ["Accurate"],
        "damage": "13-16",
        "range": 35,
        "ammo": ["5mm JHP", "5mm AP"],
        "ammo_capacity": 120,
        "type": "Gatling Gun",
        "ap": 7,
        "st": 7,
        "hands": 2,
        "attack_types": ["Burst"]
    },
    "Flamer": {
        "perks": [],
        "damage": "50-85",
        "range": 8,
        "ammo": ["Flamethrower Fuel", "Flamethrower Fuel MKII"],
        "ammo_capacity": 5,
        "type": "Flamer",
        "ap": 7,
        "st": 7,
        "hands": 2,
        "attack_types": ["Burst"]
    },
    "Incinerator": {
        "perks": ["Flameboy"],
        "damage": "110-135",
        "range": 10,
        "ammo": ["Flamethrower Fuel", "Flamethrower Fuel MKII"],
        "ammo_capacity": 5,
        "type": "Flamer",
        "ap": 7,
        "st": 7,
        "hands": 2,
        "attack_types": ["Burst"]
    },
    "Rocket Launcher": {
        "perks": ["Long Range"],
        "damage": "64-85",
        "range": 40,
        "ammo": ["Explosive Rocket", "Rocket AP"],
        "ammo_capacity": 1,
        "type": "Rocket Launcher",
        "ap": 7,
        "st": 7,
        "hands": 2,
        "attack_types": ["Single"]
    },
    "M60": {
        "perks": [],
        "damage": "30-40",
        "range": 35,
        "ammo": ["7.62mm"],
        "ammo_capacity": 100,
        "type": "Machine Gun",
        "ap": 7,
        "st": 7,
        "hands": 2,
        "attack_types": ["Burst"]
    },
    "Light Support Weapon": {
        "perks": ["Long Range"],
        "damage": "22-37",
        "range": {"S": 45, "B": 35},
        "ammo": [".223 FMJ"],
        "ammo_capacity": 30,
        "type": "Machine Gun",
        "ap": [5, 6],
        "st": 6,
        "hands": 2,
        "attack_types": ["Single", "Burst"]
    },
    "Bozar": {
        "perks": ["Long Range"],
        "damage": "50-60",
        "range": {"S": 50, "B": 40},
        "ammo": [".223 FMJ"],
        "ammo_capacity": 15,
        "type": "Sniper Rifle",
        "ap": [5, 6],
        "st": 6,
        "hands": 2,
        "attack_types": ["Single", "Burst"]
    },
    "Vindicator Minigun": {
        "perks": [],
        "damage": "20-28",
        "range": 30,
        "ammo": ["4.7mm Caseless"],
        "ammo_capacity": 100,
        "type": "Gatling Gun",
        "ap": 7,
        "st": 7,
        "hands": 2,
        "attack_types": ["Burst"]
    }
}
