energy_weapons = {
    "Wattz 1000 Laser Pistol": {
        "perks": [],
        "damage": "20-35",
        "range": 35,
        "ammo": ["Small Energy Cell"],
        "ammo_capacity": 12,
        "type": "Pistol",
        "ap": 3,
        "st": 4,
        "hands": 1,
        "attack_types": ["Single"]
    },
    "Magneto-Laser Pistol": {
        "perks": ["Penetrate"],
        "damage": "25-40",
        "range": 35,
        "ammo": ["Small Energy Cell"],
        "ammo_capacity": 12,
        "type": "Pistol",
        "ap": 3,
        "st": 4,
        "hands": 1,
        "attack_types": ["Single"]
    },
    "Wattz 2000 Laser Rifle": {
        "perks": ["Long Range"],
        "damage": "50-60",
        "range": 45,
        "ammo": ["Micro Fusion Cell"],
        "ammo_capacity": 12,
        "type": "Rifle",
        "ap": 5,
        "st": 5,
        "hands": 2,
        "attack_types": ["Single"]
    },
    "Laser Rifle (Ext. Cap.)": {
        "perks": ["Long Range"],
        "damage": "50-60",
        "range": 47,
        "ammo": ["Micro Fusion Cell"],
        "ammo_capacity": 24,
        "type": "Rifle",
        "ap": 5,
        "st": 5,
        "hands": 2,
        "attack_types": ["Single"]
    },
    "Glock 86 Plasma Pistol": {
        "perks": [],
        "damage": "30-45",
        "range": 32,
        "ammo": ["Small Energy Cell"],
        "ammo_capacity": 16,
        "type": "Pistol",
        "ap": 4,
        "st": 4,
        "hands": 1,
        "attack_types": ["Single"]
    },
    "Plasma Pistol (Ext. Cap.)": {
        "perks": [],
        "damage": "30-45",
        "range": 32,
        "ammo": ["Small Energy Cell"],
        "ammo_capacity": 32,
        "type": "Pistol",
        "ap": 4,
        "st": 4,
        "hands": 1,
        "attack_types": ["Single"]
    },
    "Winchester P94 Plasma Rifle": {
        "perks": ["Long Range"],
        "damage": "45-60",
        "range": 30,
        "ammo": ["Micro Fusion Cell"],
        "ammo_capacity": 10,
        "type": "Rifle",
        "ap": 6,
        "st": 5,
        "hands": 2,
        "attack_types": ["Single"]
    },
    "Turbo Plasma Rifle": {
        "perks": ["Long Range"],
        "damage": "50-70",
        "range": 35,
        "ammo": ["Micro Fusion Cell"],
        "ammo_capacity": 10,
        "type": "Rifle",
        "ap": 6,
        "st": 4,
        "hands": 2,
        "attack_types": ["Single"]
    },
    "L30 Gatling Laser": {
        "perks": [],
        "damage": "64-84",
        "range": 40,
        "ammo": ["Micro Fusion Cell"],
        "ammo_capacity": 30,
        "type": "Gatling Gun",
        "ap": 7,
        "st": 7,
        "hands": 2,
        "attack_types": ["Burst"]
    },
    "Alien Blaster": {
        "perks": [],
        "damage": "45-65",
        "range": 28,
        "ammo": ["Small Energy Cell"],
        "ammo_capacity": 30,
        "type": "Pistol",
        "ap": 2,
        "st": 4,
        "hands": 1,
        "attack_types": ["Single"]
    },
    "YK32 Pulse Pistol": {
        "perks": ["Penetrate"],
        "damage": "35-50",
        "range": 30,
        "ammo": ["Small Energy Cell"],
        "ammo_capacity": 5,
        "type": "Pistol",
        "ap": 3,
        "st": 4,
        "hands": 1,
        "attack_types": ["Single"]
    },
    "YK42B Pulse Rifle": {
        "perks": ["Long Range"],
        "damage": "54-78",
        "range": 48,
        "ammo": ["Micro Fusion Cell"],
        "ammo_capacity": 10,
        "type": "Rifle",
        "ap": 6,
        "st": 5,
        "hands": 2,
        "attack_types": ["Single"]
    },
    "Solar Scorcher": {
        "perks": [],
        "damage": "30-45",
        "range": 32,
        "ammo": ["Sunlight"],
        "ammo_capacity": 6,
        "type": "Pistol",
        "ap": 3,
        "st": 4,
        "hands": 1,
        "attack_types": ["Single"]
    },
    "Laser SMG": {
        "perks": [],
        "damage": "20-35",
        "range": {"S": 30, "B": 30},
        "ammo": ["Small Energy Cell"],
        "ammo_capacity": 60,
        "type": "SMG",
        "ap": 4,
        "st": 4,
        "hands": 1,
        "attack_types": ["Single", "Burst"]
    },
    "Laser Support Weapon": {
        "perks": ["Long Range"],
        "damage": "45-54",
        "range": {"S": 45, "B": 45},
        "ammo": ["Micro Fusion Cell"],
        "ammo_capacity": 30,
        "type": "SMG",
        "ap": 6,
        "st": 5,
        "hands": 2,
        "attack_types": ["Single", "Burst"]
    },
    "Phazer": {
        "perks": ["Accurate"],
        "damage": "35-60",
        "range": 25,
        "ammo": ["Micro Fusion Cell"],
        "ammo_capacity": 12,
        "type": "Pistol",
        "ap": 3,
        "st": 4,
        "hands": 1,
        "attack_types": ["Single"]
    }
}
