melee_weapons = {
    "Unarmed": {
        "perks": [],
        "damage": "1-2",
        "range": 1,
        "ammo": [],
        "ammo_capacity": 0,
        "type": "Unarmed",
        "ap": 0,
        "st": 0,
        "hands": 0,
        "attack_types": ["Single"]
    },
    "Boxing Gloves": {
        "perks": ["Knockback"],
        "damage": "1-1",
        "range": 1,
        "ammo": ["None"],
        "ammo_capacity": 0,
        "type": "Unarmed",
        "ap": 3,
        "st": 1,
        "hands": 1,
        "attack_types": ["Single"]
    },
    "Plated Boxing Gloves": {
        "perks": ["Knockback"],
        "damage": "2-5",
        "range": 1,
        "ammo": ["None"],
        "ammo_capacity": 0,
        "type": "Unarmed",
        "ap": 3,
        "st": 1,
        "hands": 1,
        "attack_types": ["Single"]
    },
    "Rock": {
        "perks": [],
        "damage": "2-5",
        "range": 1,
        "ammo": ["None"],
        "ammo_capacity": 0,
        "type": "Unarmed",
        "ap": 2,
        "st": 1,
        "hands": 1,
        "attack_types": ["Single"]
    },
    "Fool's Gold": {
        "perks": [],
        "damage": "3-6",
        "range": 1,
        "ammo": ["None"],
        "ammo_capacity": 0,
        "type": "Unarmed",
        "ap": 3,
        "st": 5,
        "hands": 1,
        "attack_types": ["Single"]
    },
    "Uranium Ore": {
        "perks": [],
        "damage": "3-6",
        "range": 1,
        "ammo": ["None"],
        "ammo_capacity": 0,
        "type": "Unarmed",
        "ap": 3,
        "st": 1,
        "hands": 1,
        "attack_types": ["Single"]
    },
    "Refined Uranium Ore": {
        "perks": [],
        "damage": "4-9",
        "range": 1,
        "ammo": ["None"],
        "ammo_capacity": 0,
        "type": "Unarmed",
        "ap": 3,
        "st": 8,
        "hands": 1,
        "attack_types": ["Single"]
    },
    "Claw": {
        "perks": [],
        "damage": "5-10",
        "range": 1,
        "ammo": ["None"],
        "ammo_capacity": 0,
        "type": "Unarmed",
        "ap": 3,
        "st": 1,
        "hands": 1,
        "attack_types": ["Single"]
    },
    "Brass Knuckles": {
        "perks": [],
        "damage": "6-17",
        "range": 1,
        "ammo": ["None"],
        "ammo_capacity": 0,
        "type": "Unarmed",
        "ap": 3,
        "st": 1,
        "hands": 1,
        "attack_types": ["Single"]
    },
    "Spiked Knuckles": {
        "perks": [],
        "damage": "9-23",
        "range": 1,
        "ammo": ["None"],
        "ammo_capacity": 0,
        "type": "Unarmed",
        "ap": 3,
        "st": 1,
        "hands": 1,
        "attack_types": ["Single"]
    },
    "Power Fist": {
        "perks": ["Penetrate"],
        "damage": "21-37",
        "range": 1,
        "ammo": ["Small Energy Cell"],
        "ammo_capacity": 50,
        "type": "Unarmed",
        "ap": 3,
        "st": 1,
        "hands": 1,
        "attack_types": ["Single"]
    },
    "Mega Power Fist": {
        "perks": ["Penetrate"],
        "damage": "25-45",
        "range": 1,
        "ammo": ["Small Energy Cell"],
        "ammo_capacity": 50,
        "type": "Unarmed",
        "ap": 3,
        "st": 1,
        "hands": 1,
        "attack_types": ["Single"]
    },
    "Shiv": {
        "perks": [],
        "damage": "2-5",
        "range": 1,
        "ammo": [],
        "ammo_capacity": 0,
        "type": "Single-Handed",
        "ap": 3,
        "st": 3,
        "hands": 1,
        "attack_types": ["Single"]
    },
    "Knife": {
        "perks": [],
        "damage": "8-13",
        "range": 1,
        "ammo": [],
        "ammo_capacity": 0,
        "type": "Single-Handed",
        "ap": 3,
        "st": 3,
        "hands": 1,
        "attack_types": ["Single"]
    },
    "Combat Knife": {
        "perks": [],
        "damage": "13-20",
        "range": 1,
        "ammo": [],
        "ammo_capacity": 0,
        "type": "Single-Handed",
        "ap": 3,
        "st": 3,
        "hands": 1,
        "attack_types": ["Single"]
    },
    "Switchblade": {
        "perks": ["Penetrate"],
        "damage": "9-16",
        "range": 1,
        "ammo": [],
        "ammo_capacity": 0,
        "type": "Single-Handed",
        "ap": 3,
        "st": 3,
        "hands": 1,
        "attack_types": ["Single"]
    },
    "Little Jesus": {
        "perks": ["Penetrate"],
        "damage": "15-22",
        "range": 1,
        "ammo": [],
        "ammo_capacity": 0,
        "type": "Single-Handed",
        "ap": 2,
        "st": 3,
        "hands": 1,
        "attack_types": ["Single"]
    },
    "Wakizashi Blade": {
        "perks": ["Penetrate"],
        "damage": "15-27",
        "range": 1,
        "ammo": [],
        "ammo_capacity": 0,
        "type": "Single-Handed",
        "ap": 3,
        "st": 3,
        "hands": 1,
        "attack_types": ["Single"]
    },
    "Old Shovel": {
        "perks": [],
        "damage": "2-4",
        "range": 2,
        "ammo": [],
        "ammo_capacity": 0,
        "type": "Single-Handed",
        "ap": 4,
        "st": 4,
        "hands": 1,
        "attack_types": ["Single"]
    },
    "Shovel": {
        "perks": [],
        "damage": "3-6",
        "range": 2,
        "ammo": [],
        "ammo_capacity": 0,
        "type": "Single-Handed",
        "ap": 4,
        "st": 4,
        "hands": 1,
        "attack_types": ["Single"]
    },
    "Club": {
        "perks": [],
        "damage": "9-24",
        "range": 1,
        "ammo": [],
        "ammo_capacity": 0,
        "type": "Single-Handed",
        "ap": 3,
        "st": 3,
        "hands": 1,
        "attack_types": ["Single"]
    },
    "Crowbar": {
        "perks": [],
        "damage": "12-20",
        "range": 1,
        "ammo": [],
        "ammo_capacity": 0,
        "type": "Single-Handed",
        "ap": 4,
        "st": 4,
        "hands": 1,
        "attack_types": ["Single"]
    },
    "Wrench": {
        "perks": [],
        "damage": "4-7",
        "range": 1,
        "ammo": [],
        "ammo_capacity": 0,
        "type": "Single-Handed",
        "ap": 3,
        "st": 3,
        "hands": 1,
        "attack_types": ["Single"]
    },
    "Sharpened Pole": {
        "perks": [],
        "damage": "3-5",
        "range": 2,
        "ammo": [],
        "ammo_capacity": 0,
        "type": "Two-Handed",
        "ap": 4,
        "st": 4,
        "hands": 2,
        "attack_types": ["Single"]
    },
    "Spear": {
        "perks": [],
        "damage": "9-13",
        "range": 2,
        "ammo": [],
        "ammo_capacity": 0,
        "type": "Two-Handed",
        "ap": 4,
        "st": 4,
        "hands": 2,
        "attack_types": ["Single"]
    },
    "Sharpened Spear": {
        "perks": ["Penetrate"],
        "damage": "13-21",
        "range": 2,
        "ammo": [],
        "ammo_capacity": 0,
        "type": "Two-Handed",
        "ap": 4,
        "st": 4,
        "hands": 2,
        "attack_types": ["Single"]
    },
    "Sledgehammer": {
        "perks": ["Knockback"],
        "damage": "9-17",
        "range": 2,
        "ammo": [],
        "ammo_capacity": 0,
        "type": "Two-Handed",
        "ap": 4,
        "st": 4,
        "hands": 2,
        "attack_types": ["Single"]
    },
    "Super Sledge": {
        "perks": ["Knockback"],
        "damage": "36-72",
        "range": 2,
        "ammo": [],
        "ammo_capacity": 0,
        "type": "Two-Handed",
        "ap": 4,
        "st": 4,
        "hands": 2,
        "attack_types": ["Single"]
    },
    "Cattle Prod": {
        "perks": ["Accurate"],
        "damage": "13-21",
        "range": 1,
        "ammo": ["Small Energy Cell"],
        "ammo_capacity": 20,
        "type": "Single-Handed",
        "ap": 3,
        "st": 3,
        "hands": 1,
        "attack_types": ["Single"]
    },
    "Super Cattle Prod": {
        "perks": ["Accurate"],
        "damage": "40-62",
        "range": 1,
        "ammo": ["Small Energy Cell"],
        "ammo_capacity": 20,
        "type": "Single-Handed",
        "ap": 3,
        "st": 3,
        "hands": 1,
        "attack_types": ["Single"]
    },
    "Louisville Slugger": {
        "perks": ["Enhanced Knockout"],
        "damage": "24-60",
        "range": 1,
        "ammo": [],
        "ammo_capacity": 0,
        "type": "Two-Handed",
        "ap": 4,
        "st": 4,
        "hands": 2,
        "attack_types": ["Single"]
    },
    "Ripper": {
        "perks": ["Penetrate"],
        "damage": "16-33",
        "range": 1,
        "ammo": ["Small Energy Cell"],
        "ammo_capacity": 30,
        "type": "Single-Handed",
        "ap": 3,
        "st": 3,
        "hands": 1,
        "attack_types": ["Single"]
    }
}
