small_guns = {
    "10mm Pistol": {
        "perks": [],
        "damage": "8-15",
        "range": 25,
        "ammo": ["10mm JHP", "10mm AP"],
        "ammo_capacity": 12,
        "type": "Pistol",
        "ap": 3,
        "st": 4,
        "hands": 1
    },
    "14mm Pistol": {
        "perks": ["Penetrate"],
        "damage": "20-30",
        "range": 28,
        "ammo": ["14mm AP"],
        "ammo_capacity": 10,
        "type": "Pistol",
        "ap": 4,
        "st": 4,
        "hands": 1
    },
    "9mm Mauser": {
        "perks": ["Accurate"],
        "damage": "8-13",
        "range": 22,
        "ammo": ["9mm", "9mm ball"],
        "ammo_capacity": 7,
        "type": "Pistol",
        "ap": 3,
        "st": 4,
        "hands": 1
    },
    "Desert Eagle .44": {
        "perks": [],
        "damage": "12-18",
        "range": 25,
        "ammo": [".44 Magnum JHP", ".44 Magnum FMJ"],
        "ammo_capacity": 8,
        "type": "Pistol",
        "ap": 3,
        "st": 4,
        "hands": 1
    },
    "Desert Eagle (Exp. Mag.)": {
        "perks": [],
        "damage": "12-18",
        "range": 25,
        "ammo": [".44 Magnum JHP", ".44 Magnum FMJ"],
        "ammo_capacity": 10,
        "type": "Pistol",
        "ap": 3,
        "st": 4,
        "hands": 1
    },
    ".223 Pistol": {
        "perks": ["Penetrate"],
        "damage": "30-40",
        "range": 30,
        "ammo": [".223 FMJ"],
        "ammo_capacity": 5,
        "type": "Pistol",
        "ap": 5,
        "st": 4,
        "hands": 1
    },
    "Shotgun": {
        "perks": ["Accurate", "Knockback"],
        "damage": "19-27",
        "range": {"S": 20, "B": 20},
        "ammo": ["12 Gauge Shotgun Shell", "12g Slugs", "12g Flechette", "12g EMP Shells", "12g Geckos Breath"],
        "ammo_capacity": 2,
        "type": "Shotgun",
        "ap": [4, 5],
        "st": 5,
        "hands": 2
    },
    "Sawed-Off Shotgun": {
        "perks": ["Accurate", "Knockback"],
        "damage": "19-27",
        "range": {"S": 7, "B": 5},
        "ammo": ["12 Gauge Shotgun Shell", "12g Slugs", "12g Flechette", "12g EMP Shells", "12g Geckos Breath"],
        "ammo_capacity": 2,
        "type": "Shotgun",
        "ap": [4, 5],
        "st": 4,
        "hands": 1
    },
    "Combat Shotgun": {
        "perks": ["Penetrate", "Knockback"],
        "damage": "20-28",
        "range": {"S": 25, "B": 25},
        "ammo": ["12 Gauge Shotgun Shell", "12g Slugs", "12g Flechette", "12g EMP Shells", "12g Geckos Breath"],
        "ammo_capacity": 12,
        "type": "Shotgun",
        "ap": 5,
        "st": 5,
        "hands": 2
    },
    "MP9 10mm SMG": {
        "perks": [],
        "damage": "8-15",
        "range": {"S": 25, "B": 20},
        "ammo": ["10mm JHP", "10mm AP"],
        "ammo_capacity": 30,
        "type": "SMG",
        "ap": [4, 5],
        "st": 4,
        "hands": 1
    },
    "Assault Rifle": {
        "perks": ["Long Range"],
        "damage": "14-23",
        "range": {"S": 45, "B": 35},
        "ammo": ["5mm JHP", "5mm AP"],
        "ammo_capacity": 36,
        "type": "Assault Rifle",
        "ap": 5,
        "st": 5,
        "hands": 2
    },
    "Assault Rifle (Exp. Mag.)": {
        "perks": ["Long Range"],
        "damage": "14-23",
        "range": {"S": 45, "B": 35},
        "ammo": ["5mm JHP", "5mm AP"],
        "ammo_capacity": 60,
        "type": "Assault Rifle",
        "ap": 5,
        "st": 5,
        "hands": 2
    },
    "Hunting Rifle": {
        "perks": ["Long Range"],
        "damage": "8-20",
        "range": 40,
        "ammo": [".223 FMJ"],
        "ammo_capacity": 5,
        "type": "Rifle",
        "ap": 5,
        "st": 5,
        "hands": 2
    },
    "Scoped Hunting Rifle": {
        "perks": ["Scoped"],
        "damage": "8-20",
        "range": 40,
        "ammo": [".223 FMJ"],
        "ammo_capacity": 5,
        "type": "Rifle",
        "ap": 5,
        "st": 5,
        "hands": 2
    },
    "Sniper Rifle": {
        "perks": ["Long Range"],
        "damage": "20-40",
        "range": 50,
        "ammo": [".223 FMJ"],
        "ammo_capacity": 6,
        "type": "Rifle",
        "ap": 5,
        "st": 5,
        "hands": 2
    },
    "Red Ryder BB Gun": {
        "perks": [],
        "damage": "8-13",
        "range": 22,
        "ammo": ["BB's"],
        "ammo_capacity": 100,
        "type": "Rifle",
        "ap": 3,
        "st": 5,
        "hands": 2
    },
    "Jonny's BB Gun": {
        "perks": [],
        "damage": "1-3",
        "range": 22,
        "ammo": ["BB's"],
        "ammo_capacity": 100,
        "type": "Rifle",
        "ap": 3,
        "st": 5,
        "hands": 2
    },
    "Red Ryder LE BB Gun": {
        "perks": [],
        "damage": "2-4",
        "range": 32,
        "ammo": ["BB's"],
        "ammo_capacity": 100,
        "type": "Rifle",
        "ap": 3,
        "st": 5,
        "hands": 2
    },
    ".44 Magnum Revolver": {
        "perks": [],
        "damage": "16-22",
        "range": 15,
        "ammo": [".44 Magnum JHP", ".44 Magnum FMJ"],
        "ammo_capacity": 6,
        "type": "Pistol",
        "ap": 4,
        "st": 4,
        "hands": 1
    },
    ".44 Magnum (Speed Load)": {
        "perks": ["Fast Reload"],
        "damage": "16-22",
        "range": 20,
        "ammo": [".44 Magnum JHP", ".44 Magnum FMJ"],
        "ammo_capacity": 6,
        "type": "Pistol",
        "ap": 4,
        "st": 4,
        "hands": 1
    },
    "Needler Pistol": {
        "perks": ["Penetrate"],
        "damage": "15-30",
        "range": 24,
        "ammo": ["HN Needler Cartridge", "HN AP Needler Cartridge"],
        "ammo_capacity": 10,
        "type": "Pistol",
        "ap": 3,
        "st": 4,
        "hands": 1
    },
    "H&K CAWS": {
        "perks": ["Penetrate", "Knockback"],
        "damage": "20-28",
        "range": {"S": 25, "B": 25},
        "ammo": ["12 Gauge Shotgun Shell", "12g Slugs", "12g Flechette", "12g EMP Shells", "12g Geckos Breath"],
        "ammo_capacity": 18,
        "type": "Shotgun",
        "ap": 6,
        "st": 5,
        "hands": 2
    },
    "Pancor Jackhammer": {
        "perks": ["Penetrate", "Knockback"],
        "damage": "22-30",
        "range": {"S": 25, "B": 25},
        "ammo": ["12 Gauge Shotgun Shell", "12g Slugs", "12g Flechette", "12g EMP Shells", "12g Geckos Breath"],
        "ammo_capacity": 20,
        "type": "Shotgun",
        "ap": 5,
        "st": 5,
        "hands": 2
    },
    "M3A1 \"Grease Gun\" SMG": {
        "perks": [],
        "damage": "10-20",
        "range": {"S": 20, "B": 15},
        "ammo": [".45 Caliber"],
        "ammo_capacity": 60,
        "type": "SMG",
        "ap": 4,
        "st": 5,
        "hands": 1
    },
    "Tommy Gun": {
        "perks": [],
        "damage": "3-20",
        "range": {"S": 32, "B": 16},
        "ammo": [".45 Caliber"],
        "ammo_capacity": 75,
        "type": "Rifle",
        "ap": 6,
        "st": 5,
        "hands": 2
    },
    "H&K P90c": {
        "perks": [],
        "damage": "15-25",
        "range": {"S": 30, "B": 25},
        "ammo": ["10mm JHP", "10mm AP"],
        "ammo_capacity": 60,
        "type": "SMG",
        "ap": 4,
        "st": 4,
        "hands": 1
    },
    "H&K G11": {
        "perks": ["Accurate"],
        "damage": "21-34",
        "range": {"S": 35, "B": 30},
        "ammo": ["4.7mm Caseless"],
        "ammo_capacity": 45,
        "type": "Assault Rifle",
        "ap": 5,
        "st": 5,
        "hands": 1
    },
    "H&K G11E": {
        "perks": ["Accurate"],
        "damage": "27-41",
        "range": {"S": 40, "B": 35},
        "ammo": ["4.7mm Caseless"],
        "ammo_capacity": 45,
        "type": "Assault Rifle",
        "ap": 6,
        "st": 5,
        "hands": 1
    },
    "FN FAL": {
        "perks": [],
        "damage": "14-22",
        "range": {"S": 35, "B": 30},
        "ammo": ["7.62mm"],
        "ammo_capacity": 20,
        "type": "Assault Rifle",
        "ap": 5,
        "st": 5,
        "hands": 2
    },
    "FN FAL (Night Sight)": {
        "perks": [],
        "damage": "9-18",
        "range": {"S": 35, "B": 30},
        "ammo": ["7.62mm"],
        "ammo_capacity": 20,
        "type": "Assault Rifle",
        "ap": 5,
        "st": 5,
        "hands": 2
    },
    "FN FAL HPFA": {
        "perks": [],
        "damage": "15-25",
        "range": {"S": 35, "B": 30},
        "ammo": ["7.62mm"],
        "ammo_capacity": 20,
        "type": "Assault Rifle",
        "ap": 5,
        "st": 5,
        "hands": 2
    },
    "XL70E3": {
        "perks": ["Accurate"],
        "damage": "25-35",
        "range": {"S": 50, "B": 35},
        "ammo": ["5mm JHP", "5mm AP"],
        "ammo_capacity": 45,
        "type": "Assault Rifle",
        "ap": 5,
        "st": 5,
        "hands": 2
    },
    "Grenade pistol": {
        "perks": [],
        "damage": "35-60",
        "range": 20,
        "ammo": ["40mm Grenade"],
        "ammo_capacity": 1,
        "type": "Pistol",
        "ap": 5,
        "st": 5,
        "hands": 1
    },
    "M79 Grenade Launcher": {
        "perks": [],
        "damage": "50-90",
        "range": 25,
        "ammo": ["40mm Grenade"],
        "ammo_capacity": 3,
        "type": "Rifle",
        "ap": 6,
        "st": 6,
        "hands": 2
    },
    "Zip Gun": {
        "perks": [],
        "damage": "6-13",
        "range": 15,
        "ammo": ["10mm JHP", "10mm AP"],
        "ammo_capacity": 1,
        "type": "Pistol",
        "ap": 4,
        "st": 4,
        "hands": 1
    },
    "Pipe Rifle": {
        "perks": [],
        "damage": "6-13",
        "range": 20,
        "ammo": ["10mm JHP", "10mm AP"],
        "ammo_capacity": 1,
        "type": "Rifle",
        "ap": 5,
        "st": 5,
        "hands": 2
    },
    "PPK12 Gauss Pistol": {
        "perks": ["Accurate"],
        "damage": "22-35",
        "range": 50,
        "ammo": ["2mm EC"],
        "ammo_capacity": 12,
        "type": "Pistol",
        "ap": 4,
        "st": 4,
        "hands": 1
    },
    "M72 Gauss Rifle": {
        "perks": ["Long Range"],
        "damage": "30-45",
        "range": 53,
        "ammo": ["2mm EC"],
        "ammo_capacity": 20,
        "type": "Rifle",
        "ap": 6,
        "st": 5,
        "hands": 2
    }
}


