throwing_weapons = {
    "Flare": {
        "perks": [],
        "damage": "1-1",
        "range": 15,
        "ammo": [],
        "ammo_capacity": 0,
        "type": "Thrown",
        "ap": 2,
        "st": 0,
        "hands": 1,
        "attack_types": ["Single"]
    },
    "Fool's Gold (Thrown)": {
        "perks": [],
        "damage": "3-6",
        "range": 15,
        "ammo": [],
        "ammo_capacity": 0,
        "type": "Thrown",
        "ap": 4,
        "st": 5,
        "hands": 1,
        "attack_types": ["Single"]
    },
    "Plant Spike": {
        "perks": [],
        "damage": "1-2",
        "range": 15,
        "ammo": [],
        "ammo_capacity": 0,
        "type": "Thrown",
        "ap": 4,
        "st": 2,
        "hands": 1,
        "attack_types": ["Single"]
    },
    "Pashtshuur Spike": {
        "perks": [],
        "damage": "5-15",
        "range": 24,
        "ammo": [],
        "ammo_capacity": 0,
        "type": "Thrown",
        "ap": 4,
        "st": 3,
        "hands": 1,
        "attack_types": ["Single"]
    },
    "Rock (Thrown)": {
        "perks": [],
        "damage": "1-4",
        "range": 15,
        "ammo": [],
        "ammo_capacity": 0,
        "type": "Thrown",
        "ap": 4,
        "st": 1,
        "hands": 1,
        "attack_types": ["Single"]
    },
    "Uranium Ore (Thrown)": {
        "perks": [],
        "damage": "3-6",
        "range": 10,
        "ammo": [],
        "ammo_capacity": 0,
        "type": "Thrown",
        "ap": 4,
        "st": 5,
        "hands": 1,
        "attack_types": ["Single"]
    },
    "Refined Uranium Ore (Thrown)": {
        "perks": [],
        "damage": "4-9",
        "range": 8,
        "ammo": [],
        "ammo_capacity": 0,
        "type": "Thrown",
        "ap": 4,
        "st": 8,
        "hands": 1,
        "attack_types": ["Single"]
    },
    "Sharpened Pole (Thrown)": {
        "perks": [],
        "damage": "2-4",
        "range": 15,
        "ammo": [],
        "ammo_capacity": 0,
        "type": "Thrown",
        "ap": 6,
        "st": 4,
        "hands": 2,
        "attack_types": ["Single"]
    },
    "Spear (Thrown)": {
        "perks": [],
        "damage": "8-12",
        "range": 15,
        "ammo": [],
        "ammo_capacity": 0,
        "type": "Thrown",
        "ap": 6,
        "st": 4,
        "hands": 2,
        "attack_types": ["Single"]
    },
    "Sharpened Spear (Thrown)": {
        "perks": [],
        "damage": "12-20",
        "range": 15,
        "ammo": [],
        "ammo_capacity": 0,
        "type": "Thrown",
        "ap": 6,
        "st": 4,
        "hands": 2,
        "attack_types": ["Single"]
    },
    "Throwing Knife": {
        "perks": [],
        "damage": "18-40",
        "range": 15,
        "ammo": [],
        "ammo_capacity": 0,
        "type": "Thrown",
        "ap": 4,
        "st": 3,
        "hands": 1,
        "attack_types": ["Single"]
    },
    "Poisoned Throwing Knife": {
        "perks": ["Poison"],
        "damage": "18-40",
        "range": 15,
        "ammo": [],
        "ammo_capacity": 0,
        "type": "Thrown",
        "ap": 4,
        "st": 3,
        "hands": 1,
        "attack_types": ["Single"]
    },
    "Molotov Cocktail": {
        "perks": ["Fire"],
        "damage": "16-24",
        "range": 15,
        "ammo": [],
        "ammo_capacity": 0,
        "type": "Thrown",
        "ap": 5,
        "st": 3,
        "hands": 1,
        "attack_types": ["Single"]
    },
    "Grenade (Fire)": {
        "perks": ["Fire"],
        "damage": "40-80",
        "range": 15,
        "ammo": [],
        "ammo_capacity": 0,
        "type": "Thrown",
        "ap": 5,
        "st": 4,
        "hands": 1,
        "attack_types": ["Single"]
    },
    "Grenade (Frag)": {
        "perks": ["Explosive"],
        "damage": "35-60",
        "range": 15,
        "ammo": [],
        "ammo_capacity": 0,
        "type": "Thrown",
        "ap": 5,
        "st": 3,
        "hands": 1,
        "attack_types": ["Single"]
    },
    "Grenade (Plasma)": {
        "perks": ["Plasma"],
        "damage": "60-120",
        "range": 15,
        "ammo": [],
        "ammo_capacity": 0,
        "type": "Thrown",
        "ap": 4,
        "st": 4,
        "hands": 1,
        "attack_types": ["Single"]
    },
    "Grenade (Pulse)": {
        "perks": ["EMP"],
        "damage": "150-300",
        "range": 15,
        "ammo": [],
        "ammo_capacity": 0,
        "type": "Thrown",
        "ap": 4,
        "st": 4,
        "hands": 1,
        "attack_types": ["Single"]
    },
    "Dynacord Stick": {
        "perks": ["Explosive"],
        "damage": "60-100",
        "range": 9,
        "ammo": [],
        "ammo_capacity": 0,
        "type": "Thrown",
        "ap": 5,
        "st": 3,
        "hands": 1,
        "attack_types": ["Single"]
    },
    "Holy Hand Grenade": {
        "perks": ["Explosive"],
        "damage": "300-500",
        "range": 20,
        "ammo": [],
        "ammo_capacity": 0,
        "type": "Thrown",
        "ap": 4,
        "st": 2,
        "hands": 1,
        "attack_types": ["Single"]
    }
}
